In [2]:
!curl -s https://raw.githubusercontent.com/teddylee777/machine-learning/master/99-Misc/01-Colab/mecab-colab.sh | bash
!curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh

--2024-03-09 07:08:32--  https://www.dropbox.com/s/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.5.18, 2620:100:601d:18::a27d:512
Connecting to www.dropbox.com (www.dropbox.com)|162.125.5.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz [following]
--2024-03-09 07:08:32--  https://www.dropbox.com/s/dl/9xls0tgtf3edgns/mecab-0.996-ko-0.9.2.tar.gz
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc1a02983c828a6d90af3cffda80.dl.dropboxusercontent.com/cd/0/get/COveOLkw7wSbhZKlCGNOPmxpZBSpVMv9JsRKUm0Two6jFj52ojg4gaSleLFMNZtHAPaRLAeVM1NOK_cYhDGRtCerOTAvWb0eT_bIq0blPzgR5naW5kbh81ZzIsrgBa8RjfXMU9o5N4PVnEJGlwNNjzEy/file?dl=1# [following]
--2024-03-09 07:08:33--  https://uc1a02983c828a6d90af3cffda80.dl.dropboxusercontent.com/cd/0/get/COveOLkw7wSbhZKlCGNOPmxpZBSpVMv9JsRKUm0Two6jFj52ojg4gaS

In [1]:
!pip install pdfplumber
!pip install langchain
!pip install openai
!pip install tiktoken
!pip install chromadb
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 48.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 48.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.5/807.5 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.9/256.9 kB 11.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.6/66.6 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.5/138.5 kB 15.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.4/227.4 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 8.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 6.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [5]:
import pandas as pd
import numpy as np
from konlpy.tag import Hannanum

HAN = Hannanum()

def to_morphs(text):
  morps = HAN.morphs(text)
  return morps

def to_text(morps):
  text = ' '.join(morps)
  return text

def process(text):
  morps = to_morphs(text)
  text = to_text(morps)
  return text


In [6]:
test_csv = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/도배하자_QA/test.csv')
train_csv = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/도배하자_QA/train.csv')

In [9]:
test_questions = test_csv['질문'].apply(process)

print(test_questions.to_list())
train_questions = train_csv['질문_1'].to_list() + train_csv['질문_2'].to_list()
train_questions = list(map(process, train_questions))
train_questions

['방청 페인트 의 종류 에는 어떤 것들 이 있 는지 알 고 계시 ㄴ가 요 ? 뜨 어 하 ㄴ , 원목사이딩 을 사용 하 는 것 에 어떤 단점 이 있 을까 요 ?', '도배지 에 녹 은 자국 이 발생 하 는 주되 ㄴ 원인 과 그 해결 방법 은 무엇 이 ㄴ가 요 ?', '큐블럭 의 단점 을 알리 어 주 세 요 . 뜨 어 하 ㄴ , 압출법 단열판 을 사용 하 는 것 의 장점 은 무엇 이 ㄴ가 요 ?', '철골구조 를 사용 하 는 고층 건물 에서 , 단열 효과 를 높이 기 위하 ㄴ 시공 방법 은 무엇 이 있 을까 요 ?', '도배지 의 완전 하 ㄴ 건조 를 위하 어 몇 주 동안 기다리 어야 하 어 나 아 요 ?', '철근철골콘크리트 구조 가 적용 되 ㄴ 건물 의 장단점 은 무엇 이 ㄴ가 요 ?', '어떤 상황 에 개별 공간 이 더 적합한지 , 어떤 상황 에 오픈 플랜 공간 이 더 적합한지 알리 어 주 세 요 . 그리고 합지벽지 의 어떤 단점 이 있 나 요 ?', '도배지 들뜨 ㅁ 현상 이 발생 하 어 는 가장 일반적 이 ㄴ 원인 은 무엇 이 ㄴ가 요 ?', '도배지 에 얼룩 이 생기 는 다양한 원 이 ㄴ 들 에 대하 어서 자세히 알리 어 주 세 요 .', '고층 건물 을 건축 하 ㄹ 때 철골구조 가 주로 선택 되 는 이유 는 무엇 이 ㄴ가 요 ?', '유성페인트 의 환경 오염 에 대하 ㄴ 예시 를 알리 어 주 세 요 .', '훼손 과 오염 은 어떻 게 다르 ㄴ가 요 ? 뜨 어 하 ㄴ , 부 이 시ㄹ 시공 으로 인하 어 타 공하자 가 발생 하 ㄹ 가능성 이 있 나 요 ?', '철골콘크리트 구조 에서 사용 되 는 철근 의 재료적 특징 은 무엇 이 ㄴ가 요 ?"', '방염벽지 가 실크벽지 와 합지벽지 와 다른 점 은 무엇 이 ㄴ가 요 ?', '도배지 에 곰팡이 가 생기 었을 때 높 은 습도 가 원인 이 ㄴ 경우 , 습기 관리 는 어떻 게 하 어야 하 ㄹ까 요 ?"', '롱브릭타일은 어떤 종류 의 타일 이 ㄴ가 요 ? 그리고 페인트 상도재 의 역할 과 사용 방법 에 대 어 

['면진장치 가 뭐 이 야 ?',
 '내진설계 의 종류 좀 알 려 주 어',
 '철골구조 의 장점 이 뭐 이 야 ?',
 '철골철근 콘크리트 구조 가 뭐 이 야 ?',
 '철골구조 는 어떤 방식 이 있 어 ?',
 '커튼월 이 뭐 이 야 ?',
 '내진구조 가 뭐 이 야 ?',
 '중목구조 방식 이 뭐 이 야 ?',
 '기둥 - 보 구조 방식 이 뭐 이 야 ?',
 '블록구조 가 뭐 이 야',
 '철골구조 의 단점 이 뭐 이 야 ?',
 '콘크리트 구조 는 어떤 방식 이 있 어 ?',
 '철골콘크리트 구조 가 뭐 이 야 ?',
 '면진구조 가 뭐 이 야 ?',
 '철골구조 가 뭐 이 야 ?',
 '면진구조 와 제 진구조의 차이점 이 뭐 이 야 ?',
 '철근콘크리트 구조 가 뭐 이 야 ?',
 '건축물 의 구조 는 어떻 게 구분 하 어 ?',
 '조적식 구조 는 어떤 방식 이 있 어 ?',
 '목구조 는 어떤 방식 이 있 어 ?',
 '경량철골구조 가 뭐 이 야 ?',
 '석구조 가 뭐 이 야 ?',
 '화재 에 취약 하 ㄴ 철골구조 의 보완법 에 뭐 가 있 을까 ?',
 '프리케스트콘크리트 구조 가 뭐 이 야 ?',
 '제 진구조 가 뭐 이 야 ?',
 '통나무구조 방식 이 뭐 이 야 ?',
 '일반철골구조 가 뭐 이 야 ?',
 '내진설계 에서 안정성 이 높 은 순서 대로 말 하 어 주 어',
 '경량목구조 방식 이 뭐 이 야 ?',
 '조적식 구조 가 뭐 이 야 ?',
 '벽돌구조 가 뭐 이 야 ?',
 '아세톤 에 노출 되 면 어디 가 안좋 아 ?',
 '공동주택 의 실내 라돈 의 측정지점 은 어떻 게 되 어 ?',
 '소화 이 기 설치 기준 이 뭐 이 야 ?',
 '아파트 도배평수 는 어떻 게 게산해 ?',
 '방수 와 발수 의 차이 가 뭐 이 야 ?',
 '건설 이 뭐 이 야 ?',
 '토목 이 뭐 이 야 ?',
 '층간소음 의 기준 이 뭐 이 야 ?',
 '흡음 이 뭐 이 야 ?',
 '새집증후군 이 뭐 이 야 ?',
 '라돈 을 제외 하 ㄴ 공동

In [76]:
## tf idf - case 1 질문만 TF-IDF vector로 이용하는 경우
from copy import deepcopy

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from collections import deque


# documents = deepcopy(document2.insert(0, document1))

# Initialize TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(train_questions)
def find_most_close_one(query, documents):

  answers = tfidf_vectorizer.transform(documents)
  query_vec = tfidf_vectorizer.transform([query])

  answers_samples, answers_features = answers.shape

  most_close_one = None
  most_close_one_score = 0000

  for i in range(answers_samples):
    if cosine_similarity(query_vec, answers[i]) >= most_close_one_score:
      most_close_one = i
      most_close_one_score = cosine_similarity(query_vec, answers[i])

  return documents[most_close_one], most_close_one_score

def find_top_k_most_close_one(query, documents, k=3):

  # tf - idf로 벡터화
  answers = tfidf_vectorizer.transform(documents)
  query_vec = tfidf_vectorizer.transform([query])


  answers_samples, answers_features = answers.shape

  most_close_one = None
  most_close_one_score = -9999

  #queue
  queue = deque(((0,0),(0,0),(0,0)),maxlen=k)
  # queue.appendleft(most_close_one_score)

  #find top-k closest ones
  for i in range(answers_samples):
    similarity = cosine_similarity(query_vec, answers[i])

    if similarity >= most_close_one_score:
      most_close_one_score = similarity
      queue.appendleft((documents[i],most_close_one_score))
    elif similarity <= most_close_one_score and queue[1][1] <= similarity:
      queue.pop()
      queue.insert(1, (documents[i], similarity))
    elif queue[2][1] <= similarity and queue[1][1] >= similarity:
      queue.pop()
      queue.append((documents[i], similarity))


  return list(queue)







In [12]:
print(test_questions[0])
find_most_close_one(test_questions[0], train_questions)

방청 페인트 의 종류 에는 어떤 것들 이 있 는지 알 고 계시 ㄴ가 요 ? 뜨 어 하 ㄴ , 원목사이딩 을 사용 하 는 것 에 어떤 단점 이 있 을까 요 ?


('방청 페인트 의 종류 는 뭐 가 있 어 ?', array([[0.51527854]]))

In [72]:
print(test_questions[71])
find_top_k_most_close_one(test_questions[71], train_questions, k = 3)

건물 의 면진장치 는 지진 발생 시 어떻 게 작동 하 어 나 아 요 ?
deque([(0, 0), (0, 0), (0, 0)], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('내진설계 의 종류 좀 알 려 주 어', array([[0.]])), (0, 0)], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('철골구조 의 장점 이 뭐 이 야 ?', array([[0.]])), ('내진설계 의 종류 좀 알 려 주 어', array([[0.]]))], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('철골철근 콘크리트 구조 가 뭐 이 야 ?', array([[0.]])), ('철골구조 의 장점 이 뭐 이 야 ?', array([[0.]]))], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('철골구조 는 어떤 방식 이 있 어 ?', array([[0.]])), ('철골철근 콘크리트 구조 가 뭐 이 야 ?', array([[0.]]))], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('커튼월 이 뭐 이 야 ?', array([[0.]])), ('철골구조 는 어떤 방식 이 있 어 ?', array([[0.]]))], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('내진구조 가 뭐 이 야 ?', array([[0.]])), ('커튼월 이 뭐 이 야 ?', array([[0.]]))], maxlen=3)
deque([('면진장치 가 뭐 이 야 ?', array([[0.52822835]])), ('중목구조 방식 이 뭐 이 야 ?', array([[0.]])), ('내진구조 가 뭐 이 야 ?', array(

[('면진장치 가 뭐 이 야 ?', array([[0.52822835]])),
 ('면진장치 에 사용 되 는 주요 기술 은 무엇 이 ㄴ가 요 ?', array([[0.29159937]])),
 ('이산화탄소 소화기 의 작동 원리 가 무엇 이 ㄴ가 요 ?', array([[0.28428615]]))]

In [ ]:
from tqdm import tqdm

records = []
for i in tqdm(range(len(test_questions))):
    query = [test_questions[i]]
    query_result = find_top_k_most_close_one(test_questions[i], train_questions, k = 3)
    questions, scores = zip(*query_result)
    record = query + list(questions) + list(scores)
    records.append(record)


records_df = pd.DataFrame.from_records(
    records,
    columns = [
        'test_questions',
        'train_questions_1',
        'train_questions_2',
        'train_questions_3',
        'train_scores_1',
        'train_scores_2',
        'train_scores_3',
        ])
records_df.to_csv('/content/drive/MyDrive/Colab Notebooks/dacon/도배하자_QA/morps_test_train_similarity_.csv')

 22%|██▏       | 28/130 [00:35<01:55,  1.14s/it]

In [84]:
records

[['방청 페인트 의 종류 에는 어떤 것들 이 있 는지 알 고 계시 ㄴ가 요 ? 뜨 어 하 ㄴ , 원목사이딩 을 사용 하 는 것 에 어떤 단점 이 있 을까 요 ?',
  '방청 페인트 의 종류 는 뭐 가 있 어 ?',
  '원목사이딩 을 사용 하 ㄴ데 어떤 단점 이 있 을까 요 ?',
  '다공질 흡음재 의 종류 에는 어떤 것들 이 있 는지 알 ㄹ 수 있 을까 요 ?',
  array([[0.51527854]]),
  array([[0.48557361]]),
  array([[0.48130822]])],
 ['도배지 에 녹 은 자국 이 발생 하 는 주되 ㄴ 원인 과 그 해결 방법 은 무엇 이 ㄴ가 요 ?',
  '결 로가 발생 하 는 주되 ㄴ 이유 가 무엇 이 ㄴ가 요 ?',
  '벽장 부위 결 로가 발생 하 는 주되 ㄴ 원인 은 무엇 이 ㄹ까 요 ?',
  '발코니 에 결 로가 발생 하 는 주되 ㄴ 이유 는 무엇 이 ㄴ가 요 ?',
  array([[0.50305024]]),
  array([[0.49608133]]),
  array([[0.44086794]])],
 ['큐블럭 의 단점 을 알리 어 주 세 요 . 뜨 어 하 ㄴ , 압출법 단열판 을 사용 하 는 것 의 장점 은 무엇 이 ㄴ가 요 ?',
  '압출법 단열판 을 사용 하 ㄹ 때 어떤 단점 이 있 을까 요 ?',
  '큐블럭 의 단점 이 뭐 이 야 ?',
  '큐블럭 의 장점 이 뭐 이 야 ?',
  array([[0.73231319]]),
  array([[0.50785203]]),
  array([[0.50026415]])],
 ['철골구조 를 사용 하 는 고층 건물 에서 , 단열 효과 를 높이 기 위하 ㄴ 시공 방법 은 무엇 이 있 을까 요 ?',
  '철골구조 가 뭐 이 야 ?',
  '인테리어 에서 천장 을 활용 하 어 공간감 을 높이 는 방법 은 무엇 이 ㄴ가 요 ?',
  '내진설계 에서 안전성 을 높이 기 위하 ㄴ 순서 는 무엇 이 ㄴ가 요 ?',
  array([[0.36379164

In [81]:
print(test_questions[1])
find_top_k_most_close_one(test_questions[1], train_questions, k = 3)

도배지 에 녹 은 자국 이 발생 하 는 주되 ㄴ 원인 과 그 해결 방법 은 무엇 이 ㄴ가 요 ?


[('결 로가 발생 하 는 주되 ㄴ 이유 가 무엇 이 ㄴ가 요 ?', array([[0.50305024]])),
 ('벽장 부위 결 로가 발생 하 는 주되 ㄴ 원인 은 무엇 이 ㄹ까 요 ?', array([[0.49608133]])),
 ('발코니 에 결 로가 발생 하 는 주되 ㄴ 이유 는 무엇 이 ㄴ가 요 ?', array([[0.44086794]]))]